# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dd2f2bcded978aeec858f6f1bde219f3cd49757aea61ff57bb108a242212b1ae895160e1d60592d431c7c69c8cce3553e9d4c9bfb7f50d190d827943b333d6c

test:
  secret_key_base: acf2b77a1c1b83b529930cfae82d2cab901e314572d07d8f5ff1b0639ecb736f0acdca6797d0e8328cc224dcbf63abe8976c957690e68c4eaa63973d86110ef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
